/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/contacts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Contacts */
        get: operations["list_contacts_api_v1_contacts_get"];
        put?: never;
        /** Create Contact */
        post: operations["create_contact_api_v1_contacts_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/contacts/tags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Tags
         * @description Return all unique tags used across the user's contacts.
         */
        get: operations["list_tags_api_v1_contacts_tags_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/contacts/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Contact Stats
         * @description Return aggregate contact stats for the dashboard.
         */
        get: operations["contact_stats_api_v1_contacts_stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/contacts/{contact_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Contact */
        get: operations["get_contact_api_v1_contacts__contact_id__get"];
        /** Update Contact */
        put: operations["update_contact_api_v1_contacts__contact_id__put"];
        post?: never;
        /** Delete Contact */
        delete: operations["delete_contact_api_v1_contacts__contact_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/contacts/{contact_id}/duplicates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Find Contact Duplicates
         * @description Find possible duplicates for a specific contact.
         */
        get: operations["find_contact_duplicates_api_v1_contacts__contact_id__duplicates_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/contacts/{contact_id}/merge/{other_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Merge Contact Pair
         * @description Merge other_id into contact_id. Returns the surviving contact.
         */
        post: operations["merge_contact_pair_api_v1_contacts__contact_id__merge__other_id__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/contacts/import/csv": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Import Contacts Csv */
        post: operations["import_contacts_csv_api_v1_contacts_import_csv_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/contacts/import/linkedin": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Import Linkedin Csv
         * @description Import contacts from LinkedIn Connections.csv export.
         */
        post: operations["import_linkedin_csv_api_v1_contacts_import_linkedin_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/contacts/import/linkedin-messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Import Linkedin Messages
         * @description Import LinkedIn messages.csv and create interactions matched to existing contacts.
         */
        post: operations["import_linkedin_messages_api_v1_contacts_import_linkedin_messages_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/contacts/sync/google": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Sync Google Contacts
         * @description Dispatch a background Google Contacts sync.
         *
         *     Returns immediately. A notification is created when sync completes.
         */
        post: operations["sync_google_contacts_api_v1_contacts_sync_google_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/contacts/sync/google-calendar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Sync Google Calendar
         * @description Dispatch a background Google Calendar sync.
         *
         *     Returns immediately. A notification is created when sync completes.
         */
        post: operations["sync_google_calendar_api_v1_contacts_sync_google_calendar_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/contacts/sync/twitter": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Sync Twitter
         * @description Dispatch a background Twitter sync (DMs + mentions + bios).
         *
         *     Returns immediately. A notification is created when sync completes.
         */
        post: operations["sync_twitter_api_v1_contacts_sync_twitter_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/contacts/scores/recalculate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Recalculate Scores
         * @description Recalculate relationship scores for all contacts of the authenticated user.
         */
        post: operations["recalculate_scores_api_v1_contacts_scores_recalculate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/contacts/{contact_id}/refresh-bios": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Refresh Contact Bios
         * @description Check for bio updates on Twitter and Telegram for a single contact.
         *
         *     Rate-limited to once per 24 hours per contact.
         */
        post: operations["refresh_contact_bios_api_v1_contacts__contact_id__refresh_bios_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/contacts/{contact_id}/interactions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Interactions */
        get: operations["list_interactions_api_v1_contacts__contact_id__interactions_get"];
        put?: never;
        /** Create Interaction */
        post: operations["create_interaction_api_v1_contacts__contact_id__interactions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register */
        post: operations["register_api_v1_auth_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_api_v1_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/google/accounts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Google Accounts */
        get: operations["list_google_accounts_api_v1_auth_google_accounts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/google/accounts/{account_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove Google Account */
        delete: operations["remove_google_account_api_v1_auth_google_accounts__account_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/google/url": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Google Oauth Url
         * @description Return the Google OAuth consent screen URL.
         */
        get: operations["google_oauth_url_api_v1_auth_google_url_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/google/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Google Callback
         * @description Exchange a Google authorization code for a JWT access token.
         *
         *     - Validates the ``state`` parameter against the server-side nonce store
         *       to prevent CSRF attacks.
         *     - If a user with the returned email already exists, update their refresh token.
         *     - Otherwise create a new account from the Google profile information.
         */
        post: operations["google_callback_api_v1_auth_google_callback_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/suggestions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Suggestions
         * @description List pending follow-up suggestions for the current user, with contact info.
         */
        get: operations["list_suggestions_api_v1_suggestions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/suggestions/digest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Digest
         * @description Return the weekly digest data for the current user.
         */
        get: operations["get_digest_api_v1_suggestions_digest_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/suggestions/{suggestion_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Update Suggestion
         * @description Update suggestion status.
         *
         *     - **sent**: marks sent, updates contact.last_followup_at
         *     - **snoozed**: accepts snooze_until or scheduled_for datetime
         *     - **dismissed**: marks dismissed
         */
        put: operations["update_suggestion_api_v1_suggestions__suggestion_id__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/suggestions/generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Generate Suggestions
         * @description Manually trigger suggestion generation for the current user.
         */
        post: operations["generate_suggestions_api_v1_suggestions_generate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/suggestions/{suggestion_id}/regenerate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Regenerate Suggestion
         * @description Re-generate the AI-drafted message for an existing suggestion.
         */
        post: operations["regenerate_suggestion_api_v1_suggestions__suggestion_id__regenerate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/telegram/connect": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Telegram Connect
         * @description Initiate Telegram login by sending an OTP to *phone*.
         *
         *     The returned ``phone_code_hash`` must be passed back to
         *     ``POST /api/v1/auth/telegram/verify``.
         */
        post: operations["telegram_connect_api_v1_auth_telegram_connect_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/telegram/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Telegram Verify
         * @description Complete Telegram sign-in with the OTP code.
         *
         *     On success the session is stored and the user is connected to Telegram.
         */
        post: operations["telegram_verify_api_v1_auth_telegram_verify_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/telegram/verify-2fa": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Telegram Verify 2Fa
         * @description Complete Telegram sign-in for accounts with two-step verification enabled.
         *
         *     Must be called after ``/verify`` returns ``requires_2fa: true``.
         */
        post: operations["telegram_verify_2fa_api_v1_auth_telegram_verify_2fa_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/contacts/sync/telegram": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Sync Telegram
         * @description Dispatch a background Telegram sync for the authenticated user.
         *
         *     Returns immediately with status "started". A notification is created
         *     when the sync completes.
         */
        post: operations["sync_telegram_api_v1_contacts_sync_telegram_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/contacts/{contact_id}/telegram/common-groups": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Common Groups
         * @description Return Telegram groups in common with a contact.
         *
         *     Results are cached on the contact for 24 hours to avoid repeated Telegram API calls.
         */
        get: operations["get_common_groups_api_v1_contacts__contact_id__telegram_common_groups_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/identity/matches": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Pending Matches
         * @description List all pending identity matches for the authenticated user's contacts.
         */
        get: operations["list_pending_matches_api_v1_identity_matches_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/identity/matches/{match_id}/merge": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Confirm Merge
         * @description Confirm and execute a pending identity match merge.
         */
        post: operations["confirm_merge_api_v1_identity_matches__match_id__merge_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/identity/matches/{match_id}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reject Match
         * @description Reject a pending identity match (mark as rejected).
         */
        post: operations["reject_match_api_v1_identity_matches__match_id__reject_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/identity/scan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Trigger Scan
         * @description Trigger a full identity resolution scan for the current user's contacts.
         */
        post: operations["trigger_scan_api_v1_identity_scan_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/twitter/url": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Twitter Auth Url
         * @description Return a Twitter OAuth 2.0 authorization URL.
         */
        get: operations["get_twitter_auth_url_api_v1_auth_twitter_url_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/twitter/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Twitter Callback
         * @description Exchange Twitter authorization code for tokens and store on user.
         */
        post: operations["twitter_callback_api_v1_auth_twitter_callback_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/notifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Notifications */
        get: operations["list_notifications_api_v1_notifications_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/notifications/unread-count": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Unread Count */
        get: operations["unread_count_api_v1_notifications_unread_count_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/notifications/read-all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Mark All Read */
        put: operations["mark_all_read_api_v1_notifications_read_all_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/notifications/{notification_id}/read": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Mark Read */
        put: operations["mark_read_api_v1_notifications__notification_id__read_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health Check */
        get: operations["health_check_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** BioRefreshData */
        BioRefreshData: {
            /** Twitter Bio Changed */
            twitter_bio_changed?: boolean | null;
            /** Telegram Bio Changed */
            telegram_bio_changed?: boolean | null;
            /** Skipped */
            skipped?: boolean | null;
            /** Reason */
            reason?: string | null;
        };
        /** Body_import_contacts_csv_api_v1_contacts_import_csv_post */
        Body_import_contacts_csv_api_v1_contacts_import_csv_post: {
            /**
             * File
             * Format: binary
             */
            file: string;
        };
        /** Body_import_linkedin_csv_api_v1_contacts_import_linkedin_post */
        Body_import_linkedin_csv_api_v1_contacts_import_linkedin_post: {
            /**
             * File
             * Format: binary
             */
            file: string;
        };
        /** Body_import_linkedin_messages_api_v1_contacts_import_linkedin_messages_post */
        Body_import_linkedin_messages_api_v1_contacts_import_linkedin_messages_post: {
            /**
             * File
             * Format: binary
             */
            file: string;
        };
        /** Body_login_api_v1_auth_login_post */
        Body_login_api_v1_auth_login_post: {
            /** Grant Type */
            grant_type?: string | null;
            /** Username */
            username: string;
            /** Password */
            password: string;
            /**
             * Scope
             * @default
             */
            scope: string;
            /** Client Id */
            client_id?: string | null;
            /** Client Secret */
            client_secret?: string | null;
        };
        /** ContactCreate */
        ContactCreate: {
            /** Full Name */
            full_name?: string | null;
            /** Given Name */
            given_name?: string | null;
            /** Family Name */
            family_name?: string | null;
            /**
             * Emails
             * @default []
             */
            emails: string[];
            /**
             * Phones
             * @default []
             */
            phones: string[];
            /** Company */
            company?: string | null;
            /** Title */
            title?: string | null;
            /** Twitter Handle */
            twitter_handle?: string | null;
            /** Twitter Bio */
            twitter_bio?: string | null;
            /** Telegram Username */
            telegram_username?: string | null;
            /** Telegram Bio */
            telegram_bio?: string | null;
            /** Linkedin Url */
            linkedin_url?: string | null;
            /** Avatar Url */
            avatar_url?: string | null;
            /**
             * Tags
             * @default []
             */
            tags: string[];
            /** Notes */
            notes?: string | null;
            /**
             * Priority Level
             * @default medium
             */
            priority_level: string;
            /** Source */
            source?: string | null;
        };
        /** ContactListResponse */
        ContactListResponse: {
            /** Data */
            data: components["schemas"]["ContactResponse"][];
            /** Error */
            error?: string | null;
            meta: components["schemas"]["PaginationMeta"];
        };
        /** ContactResponse */
        ContactResponse: {
            /** Full Name */
            full_name?: string | null;
            /** Given Name */
            given_name?: string | null;
            /** Family Name */
            family_name?: string | null;
            /**
             * Emails
             * @default []
             */
            emails: string[];
            /**
             * Phones
             * @default []
             */
            phones: string[];
            /** Company */
            company?: string | null;
            /** Title */
            title?: string | null;
            /** Twitter Handle */
            twitter_handle?: string | null;
            /** Twitter Bio */
            twitter_bio?: string | null;
            /** Telegram Username */
            telegram_username?: string | null;
            /** Telegram Bio */
            telegram_bio?: string | null;
            /** Linkedin Url */
            linkedin_url?: string | null;
            /** Avatar Url */
            avatar_url?: string | null;
            /**
             * Tags
             * @default []
             */
            tags: string[];
            /** Notes */
            notes?: string | null;
            /**
             * Priority Level
             * @default medium
             */
            priority_level: string;
            /** Source */
            source?: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
            /** Relationship Score */
            relationship_score: number;
            /** Last Interaction At */
            last_interaction_at?: string | null;
            /** Last Followup At */
            last_followup_at?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Updated At */
            updated_at?: string | null;
        };
        /** ContactStatsData */
        ContactStatsData: {
            /** Total */
            total: number;
            /** Strong */
            strong: number;
            /** Active */
            active: number;
            /** Dormant */
            dormant: number;
        };
        /** ContactSummaryData */
        ContactSummaryData: {
            /** Id */
            id: string;
            /** Full Name */
            full_name?: string | null;
            /** Given Name */
            given_name?: string | null;
            /** Family Name */
            family_name?: string | null;
            /**
             * Emails
             * @default []
             */
            emails: string[];
            /**
             * Phones
             * @default []
             */
            phones: string[];
            /** Company */
            company?: string | null;
            /** Title */
            title?: string | null;
            /** Twitter Handle */
            twitter_handle?: string | null;
            /** Telegram Username */
            telegram_username?: string | null;
            /** Linkedin Url */
            linkedin_url?: string | null;
            /**
             * Tags
             * @default []
             */
            tags: string[];
            /** Notes */
            notes?: string | null;
            /** Source */
            source?: string | null;
        };
        /** ContactUpdate */
        ContactUpdate: {
            /** Full Name */
            full_name?: string | null;
            /** Given Name */
            given_name?: string | null;
            /** Family Name */
            family_name?: string | null;
            /** Emails */
            emails?: string[] | null;
            /** Phones */
            phones?: string[] | null;
            /** Company */
            company?: string | null;
            /** Title */
            title?: string | null;
            /** Twitter Handle */
            twitter_handle?: string | null;
            /** Twitter Bio */
            twitter_bio?: string | null;
            /** Telegram Username */
            telegram_username?: string | null;
            /** Linkedin Url */
            linkedin_url?: string | null;
            /** Tags */
            tags?: string[] | null;
            /** Notes */
            notes?: string | null;
            /** Priority Level */
            priority_level?: string | null;
            /** Source */
            source?: string | null;
        };
        /** CsvImportResult */
        CsvImportResult: {
            /** Created */
            created: Record<string, never>[];
            /** Errors */
            errors: string[];
        };
        /** DeletedData */
        DeletedData: {
            /** Id */
            id: string;
            /** Deleted */
            deleted: boolean;
        };
        /** DuplicateContactData */
        DuplicateContactData: {
            /** Id */
            id: string;
            /** Full Name */
            full_name?: string | null;
            /** Given Name */
            given_name?: string | null;
            /** Family Name */
            family_name?: string | null;
            /**
             * Emails
             * @default []
             */
            emails: string[];
            /**
             * Phones
             * @default []
             */
            phones: string[];
            /** Company */
            company?: string | null;
            /** Title */
            title?: string | null;
            /** Twitter Handle */
            twitter_handle?: string | null;
            /** Telegram Username */
            telegram_username?: string | null;
            /** Score */
            score: number;
        };
        /** Envelope[BioRefreshData] */
        Envelope_BioRefreshData_: {
            data?: components["schemas"]["BioRefreshData"] | null;
            /** Error */
            error?: string | null;
            /** Meta */
            meta?: Record<string, never> | null;
        };
        /** Envelope[ContactResponse] */
        Envelope_ContactResponse_: {
            data?: components["schemas"]["ContactResponse"] | null;
            /** Error */
            error?: string | null;
            /** Meta */
            meta?: Record<string, never> | null;
        };
        /** Envelope[ContactStatsData] */
        Envelope_ContactStatsData_: {
            data?: components["schemas"]["ContactStatsData"] | null;
            /** Error */
            error?: string | null;
            /** Meta */
            meta?: Record<string, never> | null;
        };
        /** Envelope[CsvImportResult] */
        Envelope_CsvImportResult_: {
            data?: components["schemas"]["CsvImportResult"] | null;
            /** Error */
            error?: string | null;
            /** Meta */
            meta?: Record<string, never> | null;
        };
        /** Envelope[DeletedData] */
        Envelope_DeletedData_: {
            data?: components["schemas"]["DeletedData"] | null;
            /** Error */
            error?: string | null;
            /** Meta */
            meta?: Record<string, never> | null;
        };
        /** Envelope[FollowUpResponse] */
        Envelope_FollowUpResponse_: {
            data?: components["schemas"]["FollowUpResponse"] | null;
            /** Error */
            error?: string | null;
            /** Meta */
            meta?: Record<string, never> | null;
        };
        /** Envelope[IdentityMatchData] */
        Envelope_IdentityMatchData_: {
            data?: components["schemas"]["IdentityMatchData"] | null;
            /** Error */
            error?: string | null;
            /** Meta */
            meta?: Record<string, never> | null;
        };
        /** Envelope[InteractionResponse] */
        Envelope_InteractionResponse_: {
            data?: components["schemas"]["InteractionResponse"] | null;
            /** Error */
            error?: string | null;
            /** Meta */
            meta?: Record<string, never> | null;
        };
        /** Envelope[LinkedInImportResult] */
        Envelope_LinkedInImportResult_: {
            data?: components["schemas"]["LinkedInImportResult"] | null;
            /** Error */
            error?: string | null;
            /** Meta */
            meta?: Record<string, never> | null;
        };
        /** Envelope[LinkedInMessagesImportResult] */
        Envelope_LinkedInMessagesImportResult_: {
            data?: components["schemas"]["LinkedInMessagesImportResult"] | null;
            /** Error */
            error?: string | null;
            /** Meta */
            meta?: Record<string, never> | null;
        };
        /** Envelope[MarkedData] */
        Envelope_MarkedData_: {
            data?: components["schemas"]["MarkedData"] | null;
            /** Error */
            error?: string | null;
            /** Meta */
            meta?: Record<string, never> | null;
        };
        /** Envelope[MergedContactData] */
        Envelope_MergedContactData_: {
            data?: components["schemas"]["MergedContactData"] | null;
            /** Error */
            error?: string | null;
            /** Meta */
            meta?: Record<string, never> | null;
        };
        /** Envelope[NotificationReadData] */
        Envelope_NotificationReadData_: {
            data?: components["schemas"]["NotificationReadData"] | null;
            /** Error */
            error?: string | null;
            /** Meta */
            meta?: Record<string, never> | null;
        };
        /** Envelope[OAuthUrlData] */
        Envelope_OAuthUrlData_: {
            data?: components["schemas"]["OAuthUrlData"] | null;
            /** Error */
            error?: string | null;
            /** Meta */
            meta?: Record<string, never> | null;
        };
        /** Envelope[RegenerateResult] */
        Envelope_RegenerateResult_: {
            data?: components["schemas"]["RegenerateResult"] | null;
            /** Error */
            error?: string | null;
            /** Meta */
            meta?: Record<string, never> | null;
        };
        /** Envelope[ScanResultData] */
        Envelope_ScanResultData_: {
            data?: components["schemas"]["ScanResultData"] | null;
            /** Error */
            error?: string | null;
            /** Meta */
            meta?: Record<string, never> | null;
        };
        /** Envelope[ScoresRecalculatedData] */
        Envelope_ScoresRecalculatedData_: {
            data?: components["schemas"]["ScoresRecalculatedData"] | null;
            /** Error */
            error?: string | null;
            /** Meta */
            meta?: Record<string, never> | null;
        };
        /** Envelope[SyncStartedData] */
        Envelope_SyncStartedData_: {
            data?: components["schemas"]["SyncStartedData"] | null;
            /** Error */
            error?: string | null;
            /** Meta */
            meta?: Record<string, never> | null;
        };
        /** Envelope[TelegramConnectData] */
        Envelope_TelegramConnectData_: {
            data?: components["schemas"]["TelegramConnectData"] | null;
            /** Error */
            error?: string | null;
            /** Meta */
            meta?: Record<string, never> | null;
        };
        /** Envelope[TelegramConnectedData] */
        Envelope_TelegramConnectedData_: {
            data?: components["schemas"]["TelegramConnectedData"] | null;
            /** Error */
            error?: string | null;
            /** Meta */
            meta?: Record<string, never> | null;
        };
        /** Envelope[TelegramVerifyData] */
        Envelope_TelegramVerifyData_: {
            data?: components["schemas"]["TelegramVerifyData"] | null;
            /** Error */
            error?: string | null;
            /** Meta */
            meta?: Record<string, never> | null;
        };
        /** Envelope[TokenData] */
        Envelope_TokenData_: {
            data?: components["schemas"]["TokenData"] | null;
            /** Error */
            error?: string | null;
            /** Meta */
            meta?: Record<string, never> | null;
        };
        /** Envelope[TwitterAuthUrlData] */
        Envelope_TwitterAuthUrlData_: {
            data?: components["schemas"]["TwitterAuthUrlData"] | null;
            /** Error */
            error?: string | null;
            /** Meta */
            meta?: Record<string, never> | null;
        };
        /** Envelope[TwitterConnectedData] */
        Envelope_TwitterConnectedData_: {
            data?: components["schemas"]["TwitterConnectedData"] | null;
            /** Error */
            error?: string | null;
            /** Meta */
            meta?: Record<string, never> | null;
        };
        /** Envelope[UnreadCountData] */
        Envelope_UnreadCountData_: {
            data?: components["schemas"]["UnreadCountData"] | null;
            /** Error */
            error?: string | null;
            /** Meta */
            meta?: Record<string, never> | null;
        };
        /** Envelope[UserResponse] */
        Envelope_UserResponse_: {
            data?: components["schemas"]["UserResponse"] | null;
            /** Error */
            error?: string | null;
            /** Meta */
            meta?: Record<string, never> | null;
        };
        /** Envelope[UserWithAccountsData] */
        Envelope_UserWithAccountsData_: {
            data?: components["schemas"]["UserWithAccountsData"] | null;
            /** Error */
            error?: string | null;
            /** Meta */
            meta?: Record<string, never> | null;
        };
        /** Envelope[list[DuplicateContactData]] */
        Envelope_list_DuplicateContactData__: {
            /** Data */
            data?: components["schemas"]["DuplicateContactData"][] | null;
            /** Error */
            error?: string | null;
            /** Meta */
            meta?: Record<string, never> | null;
        };
        /** Envelope[list[FollowUpResponse]] */
        Envelope_list_FollowUpResponse__: {
            /** Data */
            data?: components["schemas"]["FollowUpResponse"][] | null;
            /** Error */
            error?: string | null;
            /** Meta */
            meta?: Record<string, never> | null;
        };
        /** Envelope[list[GoogleAccountData]] */
        Envelope_list_GoogleAccountData__: {
            /** Data */
            data?: components["schemas"]["GoogleAccountData"][] | null;
            /** Error */
            error?: string | null;
            /** Meta */
            meta?: Record<string, never> | null;
        };
        /** Envelope[list[IdentityMatchData]] */
        Envelope_list_IdentityMatchData__: {
            /** Data */
            data?: components["schemas"]["IdentityMatchData"][] | null;
            /** Error */
            error?: string | null;
            /** Meta */
            meta?: Record<string, never> | null;
        };
        /** Envelope[list[InteractionResponse]] */
        Envelope_list_InteractionResponse__: {
            /** Data */
            data?: components["schemas"]["InteractionResponse"][] | null;
            /** Error */
            error?: string | null;
            /** Meta */
            meta?: Record<string, never> | null;
        };
        /** Envelope[list[dict]] */
        Envelope_list_dict__: {
            /** Data */
            data?: Record<string, never>[] | null;
            /** Error */
            error?: string | null;
            /** Meta */
            meta?: Record<string, never> | null;
        };
        /** Envelope[list[str]] */
        Envelope_list_str__: {
            /** Data */
            data?: string[] | null;
            /** Error */
            error?: string | null;
            /** Meta */
            meta?: Record<string, never> | null;
        };
        /** FollowUpResponse */
        FollowUpResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Contact Id
             * Format: uuid
             */
            contact_id: string;
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
            /** Trigger Type */
            trigger_type: string;
            /** Trigger Event Id */
            trigger_event_id?: string | null;
            /** Suggested Message */
            suggested_message: string;
            /** Suggested Channel */
            suggested_channel: string;
            /** Status */
            status: string;
            /** Scheduled For */
            scheduled_for?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Updated At */
            updated_at?: string | null;
        };
        /** GoogleAccountData */
        GoogleAccountData: {
            /** Id */
            id: string;
            /** Email */
            email: string;
            /** Created At */
            created_at?: string | null;
        };
        /** GoogleCallbackRequest */
        GoogleCallbackRequest: {
            /** Code */
            code: string;
            /** State */
            state?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** IdentityMatchData */
        IdentityMatchData: {
            /** Id */
            id: string;
            /** Contact A Id */
            contact_a_id: string;
            /** Contact B Id */
            contact_b_id?: string | null;
            contact_a?: components["schemas"]["ContactSummaryData"] | null;
            contact_b?: components["schemas"]["ContactSummaryData"] | null;
            /** Match Score */
            match_score?: number | null;
            /** Match Method */
            match_method?: string | null;
            /** Status */
            status: string;
            /** Created At */
            created_at: string;
            /** Resolved At */
            resolved_at?: string | null;
        };
        /** InteractionCreate */
        InteractionCreate: {
            /**
             * Platform
             * @default manual
             */
            platform: string;
            /**
             * Direction
             * @default outbound
             */
            direction: string;
            /** Content Preview */
            content_preview?: string | null;
            /** Raw Reference Id */
            raw_reference_id?: string | null;
            /**
             * Occurred At
             * Format: date-time
             */
            occurred_at: string;
        };
        /** InteractionResponse */
        InteractionResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Contact Id
             * Format: uuid
             */
            contact_id: string;
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
            /** Platform */
            platform: string;
            /** Direction */
            direction: string;
            /** Content Preview */
            content_preview?: string | null;
            /** Raw Reference Id */
            raw_reference_id?: string | null;
            /**
             * Occurred At
             * Format: date-time
             */
            occurred_at: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** LinkedInImportResult */
        LinkedInImportResult: {
            /** Created */
            created: number;
            /** Skipped */
            skipped: number;
            /** Errors */
            errors: string[];
        };
        /** LinkedInMessagesImportResult */
        LinkedInMessagesImportResult: {
            /** New Interactions */
            new_interactions: number;
            /** Skipped */
            skipped: number;
            /** Unmatched */
            unmatched: number;
            /** Unmatched Names */
            unmatched_names: string[];
        };
        /** MarkedData */
        MarkedData: {
            /** Marked */
            marked: boolean;
        };
        /** MergedContactData */
        MergedContactData: {
            /** Id */
            id: string;
            /** Full Name */
            full_name?: string | null;
            /** Merged Contact Id */
            merged_contact_id: string;
        };
        /** NotificationData */
        NotificationData: {
            /** Id */
            id: string;
            /** Notification Type */
            notification_type: string;
            /** Title */
            title: string;
            /** Body */
            body?: string | null;
            /** Read */
            read: boolean;
            /** Link */
            link?: string | null;
            /** Created At */
            created_at?: string | null;
        };
        /** NotificationListResponse */
        NotificationListResponse: {
            /** Data */
            data: components["schemas"]["NotificationData"][];
            /** Error */
            error?: string | null;
            meta: components["schemas"]["PaginationMeta"];
        };
        /** NotificationReadData */
        NotificationReadData: {
            /** Id */
            id: string;
            /** Read */
            read: boolean;
        };
        /** OAuthUrlData */
        OAuthUrlData: {
            /** Url */
            url: string;
            /** State */
            state: string;
        };
        /** PaginationMeta */
        PaginationMeta: {
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
            /** Total Pages */
            total_pages: number;
        };
        /** RegenerateBody */
        RegenerateBody: {
            /** Channel */
            channel?: string | null;
        };
        /** RegenerateResult */
        RegenerateResult: {
            /** Suggested Message */
            suggested_message: string;
            /** Suggested Channel */
            suggested_channel: string;
        };
        /** ScanResultData */
        ScanResultData: {
            /** Auto Merged */
            auto_merged: number;
            /** Pending Review */
            pending_review: number;
            /** Matches Found */
            matches_found: number;
        };
        /** ScoresRecalculatedData */
        ScoresRecalculatedData: {
            /** Updated */
            updated: number;
        };
        /** SuggestionUpdateBody */
        SuggestionUpdateBody: {
            /** Status */
            status: string;
            /** Scheduled For */
            scheduled_for?: string | null;
            /** Snooze Until */
            snooze_until?: string | null;
            /** Suggested Message */
            suggested_message?: string | null;
            /** Suggested Channel */
            suggested_channel?: string | null;
        };
        /** SyncStartedData */
        SyncStartedData: {
            /** Status */
            status: string;
        };
        /** Telegram2FARequest */
        Telegram2FARequest: {
            /** Password */
            password: string;
        };
        /** TelegramConnectData */
        TelegramConnectData: {
            /** Phone Code Hash */
            phone_code_hash: string;
        };
        /** TelegramConnectRequest */
        TelegramConnectRequest: {
            /** Phone */
            phone: string;
        };
        /** TelegramConnectedData */
        TelegramConnectedData: {
            /** Connected */
            connected: boolean;
            /** Username */
            username?: string | null;
        };
        /** TelegramVerifyData */
        TelegramVerifyData: {
            /** Connected */
            connected: boolean;
            /** Requires 2Fa */
            requires_2fa?: boolean | null;
            /** Username */
            username?: string | null;
        };
        /** TelegramVerifyRequest */
        TelegramVerifyRequest: {
            /** Phone */
            phone: string;
            /** Code */
            code: string;
            /** Phone Code Hash */
            phone_code_hash: string;
        };
        /** Token */
        Token: {
            /** Access Token */
            access_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
        };
        /** TokenData */
        TokenData: {
            /** Access Token */
            access_token: string;
            /** Token Type */
            token_type: string;
        };
        /** TwitterAuthUrlData */
        TwitterAuthUrlData: {
            /** Url */
            url: string;
            /** State */
            state: string;
        };
        /** TwitterCallbackRequest */
        TwitterCallbackRequest: {
            /** Code */
            code: string;
            /** State */
            state: string;
        };
        /** TwitterConnectedData */
        TwitterConnectedData: {
            /** Connected */
            connected: boolean;
            /** Username */
            username?: string | null;
        };
        /** UnreadCountData */
        UnreadCountData: {
            /** Count */
            count: number;
        };
        /** UserCreate */
        UserCreate: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
            /** Full Name */
            full_name?: string | null;
        };
        /** UserResponse */
        UserResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Email */
            email: string;
            /** Full Name */
            full_name?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Google Connected
             * @default false
             */
            google_connected: boolean;
            /** Google Email */
            google_email?: string | null;
            /**
             * Telegram Connected
             * @default false
             */
            telegram_connected: boolean;
            /** Telegram Username */
            telegram_username?: string | null;
            /**
             * Twitter Connected
             * @default false
             */
            twitter_connected: boolean;
            /** Twitter Username */
            twitter_username?: string | null;
        };
        /** UserWithAccountsData */
        UserWithAccountsData: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Email */
            email: string;
            /** Full Name */
            full_name?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Google Connected
             * @default false
             */
            google_connected: boolean;
            /** Google Email */
            google_email?: string | null;
            /**
             * Telegram Connected
             * @default false
             */
            telegram_connected: boolean;
            /** Telegram Username */
            telegram_username?: string | null;
            /**
             * Twitter Connected
             * @default false
             */
            twitter_connected: boolean;
            /** Twitter Username */
            twitter_username?: string | null;
            /**
             * Google Accounts
             * @default []
             */
            google_accounts: components["schemas"]["GoogleAccountData"][];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_contacts_api_v1_contacts_get: {
        parameters: {
            query?: {
                page?: number;
                page_size?: number;
                search?: string | null;
                tag?: string | null;
                source?: string | null;
                /** @description Filter by score tier: strong (8-10), active (4-7), dormant (0-3) */
                score?: string | null;
                /** @description Filter contacts created on or after this date (YYYY-MM-DD) */
                date_from?: string | null;
                /** @description Filter contacts created on or before this date (YYYY-MM-DD) */
                date_to?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContactListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_contact_api_v1_contacts_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ContactCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_ContactResponse_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_tags_api_v1_contacts_tags_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_list_str__"];
                };
            };
        };
    };
    contact_stats_api_v1_contacts_stats_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_ContactStatsData_"];
                };
            };
        };
    };
    get_contact_api_v1_contacts__contact_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                contact_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_ContactResponse_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_contact_api_v1_contacts__contact_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                contact_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ContactUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_ContactResponse_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_contact_api_v1_contacts__contact_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                contact_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_DeletedData_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    find_contact_duplicates_api_v1_contacts__contact_id__duplicates_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                contact_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_list_DuplicateContactData__"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    merge_contact_pair_api_v1_contacts__contact_id__merge__other_id__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                contact_id: string;
                other_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_MergedContactData_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    import_contacts_csv_api_v1_contacts_import_csv_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_import_contacts_csv_api_v1_contacts_import_csv_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_CsvImportResult_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    import_linkedin_csv_api_v1_contacts_import_linkedin_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_import_linkedin_csv_api_v1_contacts_import_linkedin_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_LinkedInImportResult_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    import_linkedin_messages_api_v1_contacts_import_linkedin_messages_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_import_linkedin_messages_api_v1_contacts_import_linkedin_messages_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_LinkedInMessagesImportResult_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sync_google_contacts_api_v1_contacts_sync_google_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_SyncStartedData_"];
                };
            };
        };
    };
    sync_google_calendar_api_v1_contacts_sync_google_calendar_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_SyncStartedData_"];
                };
            };
        };
    };
    sync_twitter_api_v1_contacts_sync_twitter_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_SyncStartedData_"];
                };
            };
        };
    };
    recalculate_scores_api_v1_contacts_scores_recalculate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_ScoresRecalculatedData_"];
                };
            };
        };
    };
    refresh_contact_bios_api_v1_contacts__contact_id__refresh_bios_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                contact_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_BioRefreshData_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_interactions_api_v1_contacts__contact_id__interactions_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                contact_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_list_InteractionResponse__"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_interaction_api_v1_contacts__contact_id__interactions_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                contact_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InteractionCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_InteractionResponse_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    register_api_v1_auth_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_UserResponse_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/x-www-form-urlencoded": components["schemas"]["Body_login_api_v1_auth_login_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Token"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    me_api_v1_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_UserWithAccountsData_"];
                };
            };
        };
    };
    list_google_accounts_api_v1_auth_google_accounts_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_list_GoogleAccountData__"];
                };
            };
        };
    };
    remove_google_account_api_v1_auth_google_accounts__account_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                account_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_DeletedData_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    google_oauth_url_api_v1_auth_google_url_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_OAuthUrlData_"];
                };
            };
        };
    };
    google_callback_api_v1_auth_google_callback_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GoogleCallbackRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_TokenData_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_suggestions_api_v1_suggestions_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_list_dict__"];
                };
            };
        };
    };
    get_digest_api_v1_suggestions_digest_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_list_dict__"];
                };
            };
        };
    };
    update_suggestion_api_v1_suggestions__suggestion_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                suggestion_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SuggestionUpdateBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_FollowUpResponse_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    generate_suggestions_api_v1_suggestions_generate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_list_FollowUpResponse__"];
                };
            };
        };
    };
    regenerate_suggestion_api_v1_suggestions__suggestion_id__regenerate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                suggestion_id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["RegenerateBody"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_RegenerateResult_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    telegram_connect_api_v1_auth_telegram_connect_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TelegramConnectRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_TelegramConnectData_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    telegram_verify_api_v1_auth_telegram_verify_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TelegramVerifyRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_TelegramVerifyData_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    telegram_verify_2fa_api_v1_auth_telegram_verify_2fa_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Telegram2FARequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_TelegramConnectedData_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sync_telegram_api_v1_contacts_sync_telegram_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_SyncStartedData_"];
                };
            };
        };
    };
    get_common_groups_api_v1_contacts__contact_id__telegram_common_groups_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                contact_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_list_dict__"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_pending_matches_api_v1_identity_matches_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_list_IdentityMatchData__"];
                };
            };
        };
    };
    confirm_merge_api_v1_identity_matches__match_id__merge_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                match_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_IdentityMatchData_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reject_match_api_v1_identity_matches__match_id__reject_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                match_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_IdentityMatchData_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    trigger_scan_api_v1_identity_scan_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_ScanResultData_"];
                };
            };
        };
    };
    get_twitter_auth_url_api_v1_auth_twitter_url_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_TwitterAuthUrlData_"];
                };
            };
        };
    };
    twitter_callback_api_v1_auth_twitter_callback_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TwitterCallbackRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_TwitterConnectedData_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_notifications_api_v1_notifications_get: {
        parameters: {
            query?: {
                page?: number;
                page_size?: number;
                link?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotificationListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    unread_count_api_v1_notifications_unread_count_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_UnreadCountData_"];
                };
            };
        };
    };
    mark_all_read_api_v1_notifications_read_all_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_MarkedData_"];
                };
            };
        };
    };
    mark_read_api_v1_notifications__notification_id__read_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                notification_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_NotificationReadData_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_check_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
}
